import RafflePage from "@/components/RafflePage";
import Head from "next/head";
import React from "react";

const Raffle = () => {
  return (
    <>
      <Head>
        <title>Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RafflePage />
    </>
  );
};
export default Raffle;
